"""
Pydantic 数据模型模块
"""

# 基础模型
from .base import (
    BaseSchema,
    TimestampMixin,
    ResponseStatus,
    BaseResponse,
    PaginationParams,
    PaginatedResponse,
    ErrorDetail,
    ValidationError,
    HealthStatus,
)

# 事件链模型
from .event_chain import (
    RelationType,
    EventChain,
    EventChainCreate,
    EventChainUpdate,
    EventChainResponse,
    EventChainBatch,
    EventChainQuery,
    EventChainStatistics,
    EventChainValidation,
)

# 图数据模型
from .graph import (
    NodeType,
    EventType,
    RiskLevel,
    ImpactLevel,
    Node,
    FireEventNode,
    HazardNode,
    ConsequenceNode,
    RelationshipType,
    Relationship,
    CausalRelation,
    Path,
    GraphQuery,
    QueryResult,
    PathFindingQuery,
    GraphStatistics,
    NodeCreate,
    NodeUpdate,
    RelationshipCreate,
    RelationshipUpdate,
)

# 抽取服务模型
from .extraction import (
    ProcessingStatus,
    DocumentType,
    SectionType,
    DocumentSections,
    ExtractionResult,
    QualityScore,
    ExtractionTask,
    ExtractionRequest,
    ExtractionConfig,
    LLMResponse,
    ExtractionMetrics,
    ExtractionHistory,
    BatchExtractionRequest,
    BatchExtractionResult,
    ExtractionProgress,
)

# 校验对齐模型
from .validation import (
    ValidationStatus,
    RuleType,
    TermCategory,
    TermMapping,
    ValidationRule,
    ValidationResult,
    ValidationReport,
    TermNormalizationRequest,
    TermNormalizationResult,
    LogicalConsistencyCheck,
    TemporalValidation,
    ValidationMetrics,
    ValidationConfig,
    BatchValidationRequest,
    ValidationTask,
    RuleViolation,
    QualityAssessment,
)

# 场景预测模型
from .prediction import (
    PredictionStatus,
    RiskLevel as PredictionRiskLevel,
    ScenarioType,
    EvolutionPath,
    Scene,
    ScenarioScript,
    PredictionRequest,
    PredictionResult,
    RankedPath,
    NodeMatchingResult,
    PathFindingConfig,
    RiskAssessment,
    ScenarioGeneration,
    PredictionTask,
    PredictionMetrics,
    ScenarioComparison,
    PredictionHistory,
    BatchPredictionRequest,
)

# 文档管理模型
from .document import (
    DocumentStatus,
    FileType,
    Document,
    DocumentCreate,
    DocumentUpdate,
    DocumentResponse,
    DocumentQuery,
    DocumentStatistics,
    FileUpload,
    DocumentContent,
    DocumentProcessingLog,
    DocumentBatch,
    DocumentVersion,
    DocumentMetadata,
    DocumentSearchResult,
    DocumentExport,
)

# 用户管理模型
from .user import (
    UserRole,
    UserStatus,
    User,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserLogin,
    UserSession,
    Token,
    TokenData,
    PasswordChange,
    PasswordReset,
    PasswordResetConfirm,
    UserActivity,
    UserPreferences,
    UserStatistics,
    UserQuery,
    Permission,
    RolePermission,
    UserProfile,
)

__all__ = [
    # 基础模型
    "BaseSchema",
    "TimestampMixin",
    "ResponseStatus",
    "BaseResponse",
    "PaginationParams",
    "PaginatedResponse",
    "ErrorDetail",
    "ValidationError",
    "HealthStatus",
    
    # 事件链模型
    "RelationType",
    "EventChain",
    "EventChainCreate",
    "EventChainUpdate",
    "EventChainResponse",
    "EventChainBatch",
    "EventChainQuery",
    "EventChainStatistics",
    "EventChainValidation",
    
    # 图数据模型
    "NodeType",
    "EventType",
    "RiskLevel",
    "ImpactLevel",
    "Node",
    "FireEventNode",
    "HazardNode",
    "ConsequenceNode",
    "RelationshipType",
    "Relationship",
    "CausalRelation",
    "Path",
    "GraphQuery",
    "QueryResult",
    "PathFindingQuery",
    "GraphStatistics",
    "NodeCreate",
    "NodeUpdate",
    "RelationshipCreate",
    "RelationshipUpdate",
    
    # 抽取服务模型
    "ProcessingStatus",
    "DocumentType",
    "SectionType",
    "DocumentSections",
    "ExtractionResult",
    "QualityScore",
    "ExtractionTask",
    "ExtractionRequest",
    "ExtractionConfig",
    "LLMResponse",
    "ExtractionMetrics",
    "ExtractionHistory",
    "BatchExtractionRequest",
    "BatchExtractionResult",
    "ExtractionProgress",
    
    # 校验对齐模型
    "ValidationStatus",
    "RuleType",
    "TermCategory",
    "TermMapping",
    "ValidationRule",
    "ValidationResult",
    "ValidationReport",
    "TermNormalizationRequest",
    "TermNormalizationResult",
    "LogicalConsistencyCheck",
    "TemporalValidation",
    "ValidationMetrics",
    "ValidationConfig",
    "BatchValidationRequest",
    "ValidationTask",
    "RuleViolation",
    "QualityAssessment",
    
    # 场景预测模型
    "PredictionStatus",
    "PredictionRiskLevel",
    "ScenarioType",
    "EvolutionPath",
    "Scene",
    "ScenarioScript",
    "PredictionRequest",
    "PredictionResult",
    "RankedPath",
    "NodeMatchingResult",
    "PathFindingConfig",
    "RiskAssessment",
    "ScenarioGeneration",
    "PredictionTask",
    "PredictionMetrics",
    "ScenarioComparison",
    "PredictionHistory",
    "BatchPredictionRequest",
    
    # 文档管理模型
    "DocumentStatus",
    "FileType",
    "Document",
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentResponse",
    "DocumentQuery",
    "DocumentStatistics",
    "FileUpload",
    "DocumentContent",
    "DocumentProcessingLog",
    "DocumentBatch",
    "DocumentVersion",
    "DocumentMetadata",
    "DocumentSearchResult",
    "DocumentExport",
    
    # 用户管理模型
    "UserRole",
    "UserStatus",
    "User",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserLogin",
    "UserSession",
    "Token",
    "TokenData",
    "PasswordChange",
    "PasswordReset",
    "PasswordResetConfirm",
    "UserActivity",
    "UserPreferences",
    "UserStatistics",
    "UserQuery",
    "Permission",
    "RolePermission",
    "UserProfile",
]